"""
The 167 countries/territories added beyond the original 12, verified against
live TradingEconomics slugs (see verify_slugs.py). Single source of truth -
db/schema.sql, scrape.py, and the web app's country list are all generated
from this file (see scripts that read it) rather than hand-transcribed
separately, to avoid copy-paste drift across ~170 entries.

Fields: (name, slug, iso_code, flag_emoji)
"""

EXTRA_COUNTRIES = [
    ("Afghanistan", "afghanistan", "AF", "🇦🇫"),
    ("Albania", "albania", "AL", "🇦🇱"),
    ("Algeria", "algeria", "DZ", "🇩🇿"),
    ("Angola", "angola", "AO", "🇦🇴"),
    ("Antigua and Barbuda", "antigua-and-barbuda", "AG", "🇦🇬"),
    ("Argentina", "argentina", "AR", "🇦🇷"),
    ("Armenia", "armenia", "AM", "🇦🇲"),
    ("Aruba", "aruba", "AW", "🇦🇼"),
    ("Austria", "austria", "AT", "🇦🇹"),
    ("Azerbaijan", "azerbaijan", "AZ", "🇦🇿"),
    ("Bahamas", "bahamas", "BS", "🇧🇸"),
    ("Bahrain", "bahrain", "BH", "🇧🇭"),
    ("Bangladesh", "bangladesh", "BD", "🇧🇩"),
    ("Barbados", "barbados", "BB", "🇧🇧"),
    ("Belgium", "belgium", "BE", "🇧🇪"),
    ("Belize", "belize", "BZ", "🇧🇿"),
    ("Benin", "benin", "BJ", "🇧🇯"),
    ("Bermuda", "bermuda", "BM", "🇧🇲"),
    ("Bhutan", "bhutan", "BT", "🇧🇹"),
    ("Bolivia", "bolivia", "BO", "🇧🇴"),
    ("Bosnia and Herzegovina", "bosnia-and-herzegovina", "BA", "🇧🇦"),
    ("Botswana", "botswana", "BW", "🇧🇼"),
    ("Brazil", "brazil", "BR", "🇧🇷"),
    ("Brunei", "brunei", "BN", "🇧🇳"),
    ("Bulgaria", "bulgaria", "BG", "🇧🇬"),
    ("Burkina Faso", "burkina-faso", "BF", "🇧🇫"),
    ("Burundi", "burundi", "BI", "🇧🇮"),
    ("Cambodia", "cambodia", "KH", "🇰🇭"),
    ("Cameroon", "cameroon", "CM", "🇨🇲"),
    ("Canada", "canada", "CA", "🇨🇦"),
    ("Cape Verde", "cape-verde", "CV", "🇨🇻"),
    ("Cayman Islands", "cayman-islands", "KY", "🇰🇾"),
    ("Chad", "chad", "TD", "🇹🇩"),
    ("Chile", "chile", "CL", "🇨🇱"),
    ("China", "china", "CN", "🇨🇳"),
    ("Colombia", "colombia", "CO", "🇨🇴"),
    ("Congo", "congo", "CD", "🇨🇩"),
    ("Costa Rica", "costa-rica", "CR", "🇨🇷"),
    ("Croatia", "croatia", "HR", "🇭🇷"),
    ("Cyprus", "cyprus", "CY", "🇨🇾"),
    ("Czech Republic", "czech-republic", "CZ", "🇨🇿"),
    ("Denmark", "denmark", "DK", "🇩🇰"),
    ("Djibouti", "djibouti", "DJ", "🇩🇯"),
    ("Dominica", "dominica", "DM", "🇩🇲"),
    ("Dominican Republic", "dominican-republic", "DO", "🇩🇴"),
    ("East Timor", "timor-leste", "TL", "🇹🇱"),
    ("Ecuador", "ecuador", "EC", "🇪🇨"),
    ("Egypt", "egypt", "EG", "🇪🇬"),
    ("El Salvador", "el-salvador", "SV", "🇸🇻"),
    ("Estonia", "estonia", "EE", "🇪🇪"),
    ("Ethiopia", "ethiopia", "ET", "🇪🇹"),
    ("Euro Area", "euro-area", "XE", "🇪🇺"),
    ("European Union", "european-union", "EU", "🇪🇺"),
    ("Faroe Islands", "faroe-islands", "FO", "🇫🇴"),
    ("Fiji", "fiji", "FJ", "🇫🇯"),
    ("Finland", "finland", "FI", "🇫🇮"),
    ("Gabon", "gabon", "GA", "🇬🇦"),
    ("Gambia", "gambia", "GM", "🇬🇲"),
    ("Georgia", "georgia", "GE", "🇬🇪"),
    ("Ghana", "ghana", "GH", "🇬🇭"),
    ("Greece", "greece", "GR", "🇬🇷"),
    ("Grenada", "grenada", "GD", "🇬🇩"),
    ("Guatemala", "guatemala", "GT", "🇬🇹"),
    ("Guinea", "guinea", "GN", "🇬🇳"),
    ("Guyana", "guyana", "GY", "🇬🇾"),
    ("Haiti", "haiti", "HT", "🇭🇹"),
    ("Honduras", "honduras", "HN", "🇭🇳"),
    ("Hong Kong", "hong-kong", "HK", "🇭🇰"),
    ("Hungary", "hungary", "HU", "🇭🇺"),
    ("Iceland", "iceland", "IS", "🇮🇸"),
    ("India", "india", "IN", "🇮🇳"),
    ("Indonesia", "indonesia", "ID", "🇮🇩"),
    ("Iran", "iran", "IR", "🇮🇷"),
    ("Iraq", "iraq", "IQ", "🇮🇶"),
    ("Israel", "israel", "IL", "🇮🇱"),
    ("Ivory Coast", "cote-d-ivoire", "CI", "🇨🇮"),
    ("Jamaica", "jamaica", "JM", "🇯🇲"),
    ("Jordan", "jordan", "JO", "🇯🇴"),
    ("Kazakhstan", "kazakhstan", "KZ", "🇰🇿"),
    ("Kosovo", "kosovo", "XK", "🇽🇰"),
    ("Kuwait", "kuwait", "KW", "🇰🇼"),
    ("Kyrgyzstan", "kyrgyzstan", "KG", "🇰🇬"),
    ("Laos", "laos", "LA", "🇱🇦"),
    ("Latvia", "latvia", "LV", "🇱🇻"),
    ("Lebanon", "lebanon", "LB", "🇱🇧"),
    ("Lesotho", "lesotho", "LS", "🇱🇸"),
    ("Liberia", "liberia", "LR", "🇱🇷"),
    ("Libya", "libya", "LY", "🇱🇾"),
    ("Lithuania", "lithuania", "LT", "🇱🇹"),
    ("Luxembourg", "luxembourg", "LU", "🇱🇺"),
    ("Macau", "macau", "MO", "🇲🇴"),
    ("Macedonia", "macedonia", "MK", "🇲🇰"),
    ("Madagascar", "madagascar", "MG", "🇲🇬"),
    ("Malawi", "malawi", "MW", "🇲🇼"),
    ("Malaysia", "malaysia", "MY", "🇲🇾"),
    ("Maldives", "maldives", "MV", "🇲🇻"),
    ("Mali", "mali", "ML", "🇲🇱"),
    ("Malta", "malta", "MT", "🇲🇹"),
    ("Mauritania", "mauritania", "MR", "🇲🇷"),
    ("Mauritius", "mauritius", "MU", "🇲🇺"),
    ("Mexico", "mexico", "MX", "🇲🇽"),
    ("Moldova", "moldova", "MD", "🇲🇩"),
    ("Mongolia", "mongolia", "MN", "🇲🇳"),
    ("Montenegro", "montenegro", "ME", "🇲🇪"),
    ("Morocco", "morocco", "MA", "🇲🇦"),
    ("Mozambique", "mozambique", "MZ", "🇲🇿"),
    ("Namibia", "namibia", "NA", "🇳🇦"),
    ("Nepal", "nepal", "NP", "🇳🇵"),
    ("Netherlands", "netherlands", "NL", "🇳🇱"),
    ("New Caledonia", "new-caledonia", "NC", "🇳🇨"),
    ("New Zealand", "new-zealand", "NZ", "🇳🇿"),
    ("Nicaragua", "nicaragua", "NI", "🇳🇮"),
    ("Niger", "niger", "NE", "🇳🇪"),
    ("Nigeria", "nigeria", "NG", "🇳🇬"),
    ("Norway", "norway", "NO", "🇳🇴"),
    ("Oman", "oman", "OM", "🇴🇲"),
    ("Pakistan", "pakistan", "PK", "🇵🇰"),
    ("Palestine", "palestine", "PS", "🇵🇸"),
    ("Panama", "panama", "PA", "🇵🇦"),
    ("Papua New Guinea", "papua-new-guinea", "PG", "🇵🇬"),
    ("Paraguay", "paraguay", "PY", "🇵🇾"),
    ("Peru", "peru", "PE", "🇵🇪"),
    ("Philippines", "philippines", "PH", "🇵🇭"),
    ("Poland", "poland", "PL", "🇵🇱"),
    ("Portugal", "portugal", "PT", "🇵🇹"),
    ("Puerto Rico", "puerto-rico", "PR", "🇵🇷"),
    ("Qatar", "qatar", "QA", "🇶🇦"),
    ("Republic of the Congo", "republic-of-the-congo", "CG", "🇨🇬"),
    ("Romania", "romania", "RO", "🇷🇴"),
    ("Russia", "russia", "RU", "🇷🇺"),
    ("Rwanda", "rwanda", "RW", "🇷🇼"),
    ("Sao Tome And Principe", "sao-tome-and-principe", "ST", "🇸🇹"),
    ("Saudi Arabia", "saudi-arabia", "SA", "🇸🇦"),
    ("Senegal", "senegal", "SN", "🇸🇳"),
    ("Serbia", "serbia", "RS", "🇷🇸"),
    ("Seychelles", "seychelles", "SC", "🇸🇨"),
    ("Sierra Leone", "sierra-leone", "SL", "🇸🇱"),
    ("Slovakia", "slovakia", "SK", "🇸🇰"),
    ("Slovenia", "slovenia", "SI", "🇸🇮"),
    ("Solomon Islands", "solomon-islands", "SB", "🇸🇧"),
    ("Somalia", "somalia", "SO", "🇸🇴"),
    ("South Korea", "south-korea", "KR", "🇰🇷"),
    ("Spain", "spain", "ES", "🇪🇸"),
    ("Sri Lanka", "sri-lanka", "LK", "🇱🇰"),
    ("St Kitts and Nevis", "st-kitts-and-nevis", "KN", "🇰🇳"),
    ("St Lucia", "st-lucia", "LC", "🇱🇨"),
    ("Suriname", "suriname", "SR", "🇸🇷"),
    ("Swaziland", "swaziland", "SZ", "🇸🇿"),
    ("Sweden", "sweden", "SE", "🇸🇪"),
    ("Switzerland", "switzerland", "CH", "🇨🇭"),
    ("Syria", "syria", "SY", "🇸🇾"),
    ("Taiwan", "taiwan", "TW", "🇹🇼"),
    ("Tajikistan", "tajikistan", "TJ", "🇹🇯"),
    ("Tanzania", "tanzania", "TZ", "🇹🇿"),
    ("Thailand", "thailand", "TH", "🇹🇭"),
    ("Togo", "togo", "TG", "🇹🇬"),
    ("Trinidad And Tobago", "trinidad-and-tobago", "TT", "🇹🇹"),
    ("Tunisia", "tunisia", "TN", "🇹🇳"),
    ("Turkey", "turkey", "TR", "🇹🇷"),
    ("Uganda", "uganda", "UG", "🇺🇬"),
    ("Ukraine", "ukraine", "UA", "🇺🇦"),
    ("United Arab Emirates", "united-arab-emirates", "AE", "🇦🇪"),
    ("Uruguay", "uruguay", "UY", "🇺🇾"),
    ("Vanuatu", "vanuatu", "VU", "🇻🇺"),
    ("Venezuela", "venezuela", "VE", "🇻🇪"),
    ("Vietnam", "vietnam", "VN", "🇻🇳"),
    ("Zambia", "zambia", "ZM", "🇿🇲"),
]

if __name__ == "__main__":
    print(f"{len(EXTRA_COUNTRIES)} extra countries")
    codes = [c[2] for c in EXTRA_COUNTRIES]
    slugs = [c[1] for c in EXTRA_COUNTRIES]
    assert len(codes) == len(set(codes)), "duplicate ISO code!"
    assert len(slugs) == len(set(slugs)), "duplicate slug!"
    print("no duplicates")
